### ISSUE TITLE
is there a variable that gives me the name of the rollbacked version?

### ISSUE THREAD

**Issue by frob** [ansistrano/rollback#13]
I have a drupal site that I am working on deploying with ansistrano. Drupal is very dependent on the database. I have a deployment that backs up the db the shared directory using the ansistrano_release_version with a -1 appended to the end of the file name. 

This will be the name of the release that I want to rollback to and after the rollback I would want to source that database.

Is there an ansistano variable that I can use to get the name of the release that I am rolling back to? Is there a better way of doing this?

**Comment by ricardclau** [comment]
You can try with {{ ansistrano_current_release_version.stdout }} after the setup step when it is registered

https://github.com/ansistrano/rollback/blob/master/tasks/setup.yml

**Comment by ricardclau** [comment]
Sorry, just checking this, I meant {{ ansistrano_previous_release_version.stdout }} but I guess you figured that out looking at the code
