### ISSUE TITLE
deploy variables when executing rollback role when set in group vars

### ISSUE THREAD

**Issue by marcogrossisas** [ansistrano/rollback#22]
When using group variables and in the same group are variables for ansistrano.deploy and ansistrano.rollback and we execute ansistrano.rollback role, the role also takes into account the variables of ansistrano.deploy. 

For example, we have two variable files for a inventory group:
deploy.yml that has ansistrano_before_symlink_tasks_file and ansistrano_after_symlink_tasks_file variables set
rollback.yml that has ansistrano_rollback_after_symlink_tasks_file set

Why when executing ansistrano.rollback it includes the ansistrano_before_symlink_tasks_file and ansistrano_after_symlink_tasks_file files if are set? It shuldn't be including only the files set in the rollback variables like ansistrano_rollback_after_symlink_tasks_file?

This is causing a deploy when trying a rollback because there is the ansistrano_before_symlink_tasks_file and ansistrano_after_symlink_tasks_file are defined.

Of course we can set the variables directly in the rollback playbook, but it would be interesting to know if there is a way to mantain our variable structure defined by groups.

Thanks a lot!

**Comment by ricardclau** [comment]
It looks like you have an old ansistrano.rollback version. We allowed having different task files in 3.0.0

Other than that, all group_vars are included within the group. This is an Ansible limitation, nothing to do with Ansistrano. AFAIK there is no way to overcome it apart from including different var_files or defining your variables in the playbook
