### ISSUE TITLE
ansistrano_shared_path is not defined

### ISSUE THREAD

**Issue by robertmircea** [ansistrano/rollback#3]
`rollback` does not define `ansistrano_shared_path` variable. Please make all variables available as in `deploy` project. An idea is to use the same `setup.yml`.

**Comment by ricardclau** [comment]
Why would you need that? The rollback strategy changes the symlink and deletes the broken version. 

In fact, imagine you have a deployment with a particular `ansistrano_shared_path` that you change in the following deployment. Having this variable in rollback would lead to problems whereas changing symlinks will keep everything as it was in the previous deployment

Unless, of course, I am missing something here

**Comment by ricardclau** [comment]
Ping @robertmircea
